# The GitLab Continuous Integration configuration
image: "ubuntu:22.04"

variables:
  GIT_STRATEGY: "clone"
  GIT_SUBMODULE_STRATEGY: "recursive"

before_script:
 # Disable the wget progress bar
 - echo 'show-progress = off' >> ~/.wgetrc
 - |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq &&
    apt-get install -qq \
        ant \
        autoconf \
        appstream \
        automake \
        autopoint \
        bison \
        build-essential \
        ca-certificates \
        clang \
        cmake \
        curl \
        doxygen \
        file \
        flex \
        fuse3 \
        genisoimage \
        git \
        gperf \
        intltool \
        libc6-dev-i386 \
        libexpat-dev \
        libfuse-dev \
        libfuse3-dev \
        libgmp-dev \
        libhtml-parser-perl \
        libtool \
        libfontconfig1-dev \
        libpng-dev \
        libjpeg-dev \
        libsdl2-ttf-dev \
        libsdl1.2-dev \
        llvm \
        lzip \
        m4 \
        make \
        meson \
        nasm \
        ninja-build \
        perl \
        pkg-config \
        po4a \
        protobuf-compiler \
        python3 \
        python3-mako \
        rsync \
        syslinux-utils \
        texinfo \
        wget \
        xdg-utils \
        xxd \
        zip \
        unzip \
        zstd &&
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain none

img:
    script:
     - |
        source "$HOME/.cargo/env" &&
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash &&
        cargo binstall --no-confirm --version 0.1.1 cargo-config &&
        cargo binstall --no-confirm --version 1.16.0 just &&
        cargo binstall --no-confirm --version 0.27.0 cbindgen &&
        cargo build --manifest-path installer/Cargo.toml --release &&
        PODMAN_BUILD=0 REPO_BINARY=1 make ci-img IMG_TAG=$CI_COMMIT_REF_NAME
    artifacts:
        paths:
         - build/img/
        expire_in: 1 week
