[workspace]
members = [
    "docgen",
    "drivers/ahcid",
    "drivers/alxd",
    "drivers/bgad",
    "drivers/e1000d",
    "drivers/nvmed",
    "drivers/pcid",
    "drivers/ps2d",
    "drivers/rtl8168d",
    "drivers/vboxd",
    "drivers/vesad",
    "drivers/xhcid",
    "installer",
    "kernel",
    "libs/event",
    "libs/extra",
    "libs/jpeg-decoder",
    "libs/mio",
    "libs/orbclient",
    "libs/orbfont",
    "libs/orbimage",
    "libs/orbtk",
    "libs/orbkb",
    "libs/pager",
    #TODO "libs/ralloc",
    "libs/ransid",
    "libs/same-file",
    "libs/syscall",
    "libs/tar",
    "libs/termion",
    "programs/acid",
    "programs/binutils",
    "programs/contain",
    "programs/coreutils",
    "programs/extrautils",
    "programs/games",
    "programs/init",
    "programs/ion",
    "programs/netutils",
    "programs/orbutils",
    "programs/pkgutils",
    "programs/smith",
    "programs/sodium",
    "programs/timeout",
    "programs/userutils",
    "schemes/ethernetd",
    "schemes/ipd",
    "schemes/orbital",
    "schemes/ptyd",
    "schemes/randd",
    "schemes/redoxfs",
    "schemes/tcpd",
    "schemes/udpd"
]

[replace]
"extra:0.1.0" = { path = "libs/extra" }
"jpeg-decoder:0.1.12" = { path = "libs/jpeg-decoder" }
"mio:0.6.2" = { path = "libs/mio" }
"orbclient:0.3.4" = { path = "libs/orbclient" }
"orbfont:0.1.7" = { path = "libs/orbfont" }
"orbimage:0.1.15" = { path = "libs/orbimage" }
"orbtk:0.2.19" = { path = "libs/orbtk" }
"pager:0.1.0" = { path = "libs/pager" }
"ralloc:1.0.0" = { path = "libs/ralloc" }
"ransid:0.2.7" = { path = "libs/ransid" }
"redox_event:0.1.0" = { path = "libs/event" }
"redox_syscall:0.1.17" = { path = "libs/syscall" }
"same-file:0.1.2" = { path = "libs/same-file" }
"tar:0.4.11" = { path = "libs/tar" }
"termion:1.3.0" = { path = "libs/termion" }
