[workspace]
members = [
    "docgen",
    "drivers/ahcid",
    "drivers/bgad",
    "drivers/e1000d",
    "drivers/nvmed",
    "drivers/pcid",
    "drivers/ps2d",
    "drivers/rtl8168d",
    "drivers/vboxd",
    "drivers/vesad",
    "drivers/xhcid",
    "installer",
    "kernel",
    "programs/acid",
    "programs/binutils",
    "programs/contain",
    "programs/coreutils",
    "programs/extrautils",
    "programs/games",
    "programs/init",
    "programs/ion",
    "programs/netutils",
    "programs/orbutils",
    "programs/pkgutils",
    "programs/smith",
    "programs/tar",
    "programs/userutils",
    "schemes/ethernetd",
    "schemes/ipd",
    "schemes/orbital",
    "schemes/ptyd",
    "schemes/randd",
    "schemes/redoxfs",
    "schemes/tcpd",
    "schemes/udpd"
]

[replace]
"jpeg-decoder:0.1.11" = { git = "https://github.com/redox-os/jpeg-decoder.git", branch = "single_thread" }
"liner:0.1.3" = { git = "https://github.com/redox-os/liner.git", branch = "redox" }
"termion:1.3.0" = { git = "https://github.com/redox-os/termion.git" }
